config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "users/registrations" }

  root 'games#index'

  get '/games', to: 'games#index'
  get '/games/new', to: 'games#new'
  get '/games/:id/score_input_form', to: 'games#score_input_form'
  post '/games/:id/score_input', to: 'games#score_input', as: "score_input"
  post '/games/:id', to: 'games#create'
  get '/games/:id', to: 'games#show'

  post '/bets/batch', to: 'bets#batch'
  get '/bets', to: 'bets#index'

  get '/users/add_funds_form', to: 'users#add_funds_form'
  post '/users/add_funds', to: 'users#add_funds'
  get '/users/:id', to: 'users#show'
  get 'users/:id/edit', to: 'users#edit'
  patch 'users/:id', to: 'users#update'
  get 'users/:id/games', to: 'users#games'
  

end

app/models/bet.rb
class Bet < ActiveRecord::Base

belongs_to :user
belongs_to :game
belongs_to :combo


validates :better_id, uniqueness: {scope: [:better_id, :combo_id, :game_id]}

end

app/models/combo.rb
class Combo < ActiveRecord::Base

has_many :bets

end

app/models/game.rb
class Game < ActiveRecord::Base

  has_many :bets
  has_many :users, through: :bets


  validate :game_complete


  def game_complete
    if (Time.now() <= start_time) && (completed == true)
      errors.add(:start_time, "Game has not started yet.")
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_many :bets
  has_many :games, through: :bets
  has_many :combos, through: :bets 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  
end

app/controllers/bets_controller.rb
class BetsController < ApplicationController

  def index

  end

  def new

  end

  # def create
  #   @bet = Bet.new
  # end

  def batch
    pick_ids = []
    params.each do |key, value|
      pick_ids << key if value == "true"
    end

    pick_ids.each do |pick_id|
      @bet = Bet.new(combo_id: pick_id, better_id: current_user.id, game_id: params[:game_id])
      @bet.save
    end

    user = User.find_by(id: current_user.id)
    new_balance = user.balance - (pick_ids.length * @bet.game.bet_amount)
    user.update(balance: new_balance)
    redirect_to "/games/#{params[:game_id]}"
  end
end

app/controllers/games_controller.rb
    class GamesController < ApplicationController
    before_action :authenticate_user!, except: [:index]

  def index
    @games = Game.all

    if current_user
        games_of_user = current_user.games
        #determine winner, and update winner's balance
    end
  end


  def new

  end

  def create
    start_time = DateTime.strptime(params[:start_time], "%m/%d/%Y %I:%M %p")
    @game = Game.new(name: params[:name], start_time: start_time, bet_amount: params[:bet_amount], banker_id: current_user.id, banker: current_user.username, completed: false)
    pot_reserve = @game.bet_amount * 100
    if current_user.balance < pot_reserve
        flash[:error] = "You do not have enough money to start this!"
        redirect_to "/users/add_funds_form"
    else
        current_user.update(balance: current_user.balance - pot_reserve)
        @game.save
        redirect_to "/games/#{@game.id}"
    end
  end

  def show
    @rows = []
    @row_1 = Combo.all[0..9]
    @row_2 = Combo.all[10..19]
    @row_3 = Combo.all[20..29]
    @row_4 = Combo.all[30..39]
    @row_5 = Combo.all[40..49]
    @row_6 = Combo.all[50..59]
    @row_7 = Combo.all[60..69]
    @row_8 = Combo.all[70..79]
    @row_9 = Combo.all[80..89]
    @row_10 = Combo.all[90..99]

    @rows << @row_1
    @rows << @row_2
    @rows << @row_3
    @rows << @row_4
    @rows << @row_5
    @rows << @row_6
    @rows << @row_7
    @rows << @row_8
    @rows << @row_9
    @rows << @row_10

    @game = Game.find_by(id: params[:id])
    @bets = Bet.where(game_id: @game.id)
    @pot = @game.bet_amount * 90
    @tip = @game.bet_amount * 10
    @pool = @game.bets.count * @game.bet_amount 

    if Time.now >= @game.start_time
        @game_started = true
    else
        @game_started = false
    end


    @winner = @game.winning_score
    @loser = @game.losing_score
    if @winner != 0 && @loser != 0 && @game.completed == true
        @winning_combo = ((@winner % 10).to_s + "-" + (@loser % 10).to_s)
        @winning_combo_id = Combo.find_by(pick: @winning_combo).id

        @winning_bet = Bet.where(combo_id: @winning_combo_id, game_id: @game.id)
        if @game.bets && !@winning_bet.empty?
            @winning_user = User.find((Bet.find_by(combo_id: @winning_combo_id).better_id))
        end 
    end

  end

  def score_input_form
    @game = Game.find_by(id: params[:id]) 
  end

  def score_input
    @game = Game.find_by(id: params[:id]) 
    @game.winning_score = params[:winning_score]
    @game.losing_score = params[:losing_score]
    @game.completed = true

    # If user wins
    @pot = @game.bet_amount * 90 # For user
    @tip = @game.bet_amount * 10 # For banker

    # If banker wins
    @pool = @game.bets.count * @game.bet_amount

    if @game.save
        @winner = @game.winning_score
        @loser = @game.losing_score
        if @winner != 0 && @loser != 0
            @winning_combo = ((@winner % 10).to_s + "-" + (@loser % 10).to_s)
            @winning_combo_id = Combo.find_by(pick: @winning_combo).id

            @winning_bet = Bet.find_by(combo_id: @winning_combo_id)
            if @game.bets && @winning_bet
                # User wins
                @winning_user = User.find((Bet.find_by(combo_id: @winning_combo_id).better_id))
                @new_user_balance = @winning_user.balance + @pot
                @winning_user.update(balance: @new_user_balance)
            elsif @game.bets
                # Banker wins
                @banker = User.find_by(id: @game.banker_id)
                @new_banker_balance = @banker.balance + @pot + @tip + @pool
                @banker.update(balance: @new_banker_balance)
            end 
        end

        flash[:success] = "Score Updated"
    else
        flash[:danger] = "Game has not started yet."
    end
    redirect_to "/games/#{@game.id}"
  end


end



    # response_schedule = Unirest.get("http://api.sportradar.us/nba-t3/games/2016/06/10/schedule.json?api_key=5b9xdyg9pdam7ghgq4n9pwn9").body


    # response_schedule["games"].each do |game|

    #     game_summary = Unirest.get("http://api.sportradar.us/nba-t3/games/#{game["id"]}/summary.json?api_key=5b9xdyg9pdam7ghgq4n9pwn9").body
    #     # puts "Game: #{game_summary.body}"
    #     binding.pry
        
    #     if game_summary
    #         p game_summary["away"]["points"]
    #         p game_summary["home"]["points"]
    #     end



    

    

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
    private

  def sign_up_params
    params.require(:user).permit(:username, :first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:username, :first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def games
    
    id = params[:id]
    @user = User.find(id)

    @banker_games = Game.where(banker_id: @user.id)


    @better_games = []
    user_bets = Bet.select(:better_id, :game_id).uniq.where(better_id: @user.id)
    user_bets.each do |bet|
      game = Game.find(bet.game_id)
      @better_games << game
    end

    @user_games = @banker_games + @better_games


  end

  def add_funds_form
    @user = User.find_by(id: current_user.id)
  end

  def add_funds
    @user = User.find_by(id: current_user.id)
    if @user.balance == nil
      @user.balance = 0
    end
    @user.balance += params[:balance].to_i
    @user.save
    flash[:success] = "Funds Added"
    redirect_to "/"
  end

  def show
 
  end

  def edit
    
  end

  def update
    user = User.find_by(id: current_user.id)
    user.first_name = params[:first_name]
    user.last_name = params[:last_name]
    user.username = params[:username]
    user.save
    flash[:success] = "Profile Updated"
    redirect_to "/users/#{user.id}"
  end
end
    

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bets_helper.rb
module BetsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/games/index.html.erb
<div class="container">
<div class="games-index-table">
  <div class="games-index-header">
    <h2>Games</h2>
  </div>
  <div class="games-index-body">
  <table class="table table-striped">
      <thead>
        <tr>
          <th class="row-header">ID</th>
          <th class="row-header">Games</th>
          <th class="row-header">Bet Amount</th>
          <th class="row-header">Prizes</th>
          <th class="row-header">Schedule</th>
          <th class="row-header">Banker</th>
          <th class="row-header">Scores</th>
          <th></th>
        </tr>
      </thead>
      <%@games.each do |game|%>
        <tbody>
          <tr class="index-row">
            <td class="game-index"><%= game.id %></td>
            <td class="game-index"><%= game.name %></td>
            <td class="game-index">$<%= number_with_precision(game.bet_amount, :precision => 2)%></td>
            <td class="game-index">$<%= number_with_precision(game.bet_amount * 90, :precision => 2) %></td>
            <td class="game-index"><%= game.start_time.strftime("%b %e, %l:%M %p") %></td>
            <td class="game-index"><%= game.banker %></td>
            <% if game.winning_score != 0 %>
              <td class="game-index"><%= game.winning_score.to_s + "-" + game.losing_score.to_s %></td>
            <%  else %>
              <td></td>
            <% end %>
            <td class="game-index"><a type="button" class="btn btn-primary btn-sm" id="join-button" href="/games/<%= game.id %>">Enter</a></td>
        </tbody>
      <% end %>
    </table>
    </div>
  </div>
</div>

app/views/games/new.html.erb
<div class="container">
  <div class="form-box">
    <div class="form-header">
      <h2>Start a New Game</h2>
    </div>
    <div class="form-body">
      <%= form_tag '/games/new', method: :post do %>
        <div class="form-group">
          <label>Game (Team vs Team)</label>
          <%= text_field_tag :name, nil, class: "form-control", placeholder: "Team vs Team" %>
        </div>
        <div class="form-group">
          <label>Start Time</label>
          <div class="input-group date" id="datetimepicker1">
            <%= text_field_tag :start_time, nil, class: "form-control", placeholder: "" %>
            <span class="input-group-addon">
              <span class="glyphicon glyphicon-calendar"></span>
            </span>
          </div>
        </div>
        <div class="form-group">
          <label>Bet Amount</label>
          <div class="input-group">
            <span class="input-group-addon">$</span>
            <%= text_field_tag :bet_amount, nil, class: "form-control", placeholder: "0.00" %>
          </div>
        </div>
        <%= submit_tag 'Start Game', class: "btn btn-primary new_game_button" %>
      <% end %>
    </div>
  </div>
</div>





<script type="text/javascript">
  $(function () {
    $('#datetimepicker1').datetimepicker();
  });
</script>

app/views/games/score_input_form.html.erb
<div class="container">
  <div class="form-box">
    <div class="form-header">
      <h2>Game Score</h2>
    </div>
    <div class="form-body">
      <%= form_tag score_input_path, method: :post do %>
        <div class="form-group">
          <label>Winner</label>
            <%= text_field_tag :winning_score, nil, class: "form-control" %>
        </div>
        <div class="form-group">
          <label>Loser</label>
            <%= text_field_tag :losing_score, nil, class: "form-control" %>
        </div>
        <%= submit_tag 'Update Score', class: "btn btn-primary new_game_button"  %>
        
      <% end %>
    </div>
  </div>
</div>

app/views/games/show.html.erb
<div class="game-info-div">
  <table class="game-info">
    <th>Game ID: <%= @game.id %></th>
    <th><%= @game.name %></th>
    <% if @game.completed %>
      <th>Final Score: <%= @game.winning_score.to_s + "-" + @game.losing_score.to_s %></th>
    <% end %>
    <% if !@game.completed %>
      <th>Start Time:   <%= @game.start_time.strftime("%b %e, %l:%M %p") %></th>
    <% end %>
    <th>Bet:  $<%= number_with_precision(@game.bet_amount, :precision => 2)%></th>
    <th>Pot:  $<%= number_with_precision(@pot, :precision => 2) %></th>
    <th>Banker:  <%= @game.banker %></th>

    <% if @game_started && !@game.completed %>
      <th><a href="/games/<%= @game.id %>/score_input_form">Update Score</a></th>
    <% end %>
  </table>
</div>


<div class='text-center animated bounceIn' id='winner-banner'>
  <% if @winning_user && @game.completed %>

    <%= @winning_user.username %> won $<%= number_with_precision(@pot, :precision => 2)%>

  <% elsif @game.completed %>

    <%= @game.banker %> won $<%= number_with_precision(@pot + @tip + @pool, :precision => 2)%>!

  <% end %>
</div>

<!-- If the game hasn't started, then we show the betting table -->
<% if !@game_started %>

  <%= form_tag '/bets/batch', method: :post do %>
    <table class="tg">
      <% @rows.each do |row| %>
        <tr>
          <% row.each do |combo| %>
            <% if !@bets.select { |bet| bet.combo_id == combo.id && bet.better_id == current_user.id }.empty? %>
            <!-- shows only logged in user's bets -->
              <td class="tg-qj3h">
                <span class="button-checkbox">
                  <button type="button" class="btn btn-primary current-user-buttons" data-color="primary" disabled="true"><%= combo.pick %></button>
                  <%= check_box_tag combo.id, true, true, disabled: true, :style => 'display:none' %>
                </span>
              </td>
            <% elsif !@bets.select { |bet| bet.combo_id == combo.id && bet.better_id != current_user.id }.empty? %> 
              <td class="tg-qj3h">
                <span class="button-checkbox">
                  <button type="button" class="btn btn-primary other-user-buttons" data-color="primary" disabled="true"><%= combo.pick %></button>
                  <%= check_box_tag combo.id, true, true, disabled: true,:style => 'display:none' %>
                </span>
              </td>
            <% else %>
              <td class="tg-qj3h">
                <span class="button-checkbox">
                <!-- The ones not selected -->
                  <button type="button" class="btn games-button" data-color="primary"><%= combo.pick %></button>
                  <%= check_box_tag combo.id, true, false, :style => 'display:none' %>
                </span>
              </td>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </table>
    <%= hidden_field_tag :game_id, @game.id %>
    <%= submit_tag 'Commit', :class => 'btn btn-primary games-commit-button', :id => 'commit' %>
  <% end %>

<!-- If the game has started, then everything is disabled -->
<% else %>

    <table class="tg">
      <% @rows.each do |row| %>
        <tr>
          <% row.each do |combo| %>
            <% if !@bets.select { |bet| bet.combo_id == combo.id && bet.better_id == current_user.id }.empty? %>
            <!-- shows only logged in user's bets -->
              <td class="tg-qj3h">
                <span class="button-checkbox">
                  <% if combo.id == @winning_combo_id %>
                    <button type="button" class="btn btn-primary current-user-buttons winning-combo" data-color="primary" disabled="true"><%= combo.pick %></button>
                  <% else %>
                    <button type="button" class="btn btn-primary current-user-buttons" data-color="primary" disabled="true"><%= combo.pick %></button>
                  <% end %>

                  <%= check_box_tag combo.id, true, true, disabled: true, :style => 'display:none' %>
                </span>
              </td>
            <% elsif !@bets.select { |bet| bet.combo_id == combo.id && bet.better_id != current_user.id }.empty? %> 
              <td class="tg-qj3h">
                <span class="button-checkbox">
                  <% if combo.id == @winning_combo_id %>
                    <button type="button" class="btn btn-primary other-user-buttons winning-combo" data-color="primary" disabled="true"><%= combo.pick %></button>
                  <% else %>
                    <button type="button" class="btn btn-primary other-user-buttons" data-color="primary" disabled="true"><%= combo.pick %></button>
                  <% end %>

                  <%= check_box_tag combo.id, true, true, disabled: true,:style => 'display:none' %>
                </span>
              </td>
            <% else %>
              <td class="tg-qj3h">
                <span class="button-checkbox">
                <!-- The ones not selected -->
                  <% if combo.id == @winning_combo_id %>
                    <button type="button" class="btn games-button winning-combo" data-color="primary" disabled="true"><%= combo.pick %></button>
                  <% else %>
                    <button type="button" class="btn games-button" data-color="primary" disabled="true"><%= combo.pick %></button>
                  <% end %>

                  <%= check_box_tag combo.id, true, false, :style => 'display:none' %>
                </span>
              </td>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </table>

<% end %>


<script type="text/javascript">
  

$(function () {
    $('.button-checkbox').each(function () {

        // Settings
        var $widget = $(this),
            $button = $widget.find('button'),
            $checkbox = $widget.find('input:checkbox'),
            color = $button.data('color'),
            settings = {
                on: {
                    // icon: 'glyphicon glyphicon-check'
                },
                off: {
                    // icon: 'glyphicon glyphicon-unchecked'
                }
            };

        // Event Handlers
        $button.on('click', function () {
            $checkbox.prop('checked', !$checkbox.is(':checked'));
            $checkbox.triggerHandler('change');
            updateDisplay();
        });
        $checkbox.on('change', function () {
            updateDisplay();
        });

        // Actions
        function updateDisplay() {
            var isChecked = $checkbox.is(':checked');

            // Set the button's state
            $button.data('state', (isChecked) ? "on" : "off");

            // Set the button's icon
            // $button.find('.state-icon')
            //     .removeClass()
            //     .addClass('state-icon ' + settings[$button.data('state')].icon);

            // Update the button's color
            if (isChecked) {
                $button
                    .removeClass('btn-default')
                    .addClass('btn-' + color + ' active');
            }
            else {
                $button
                    .removeClass('btn-' + color + ' active')
                    .addClass('btn-default');
            }
        }

        // Initialization
        function init() {

            updateDisplay();

            // // Inject the icon if applicable
            // if ($button.find('.state-icon').length == 0) {
            //     $button.prepend('<i class="state-icon ' + settings[$button.data('state')].icon + '"></i> ');
            // }
        }
        init();
    });
});


</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body class="<%= params[:controller] %>-<%= params[:action] %>">



  
  <nav class="navbar navbar-default" id="main-nav">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" id="logo" href="#">ScorEnd</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav pull-right" >
          <% if current_user %>
            <li><a href="/games" class="smoothScroll" id="menu">Lobby</a></li>
            <li> <a href="#about" class="smoothScroll" id="menu"> How to play</a></li>
            <li> <a href="#services" class="smoothScroll" id="menu"> Upcoming</a></li>
            <li> <a href="#team" class="smoothScroll" id="menu"> History</a></li>
            <li> <a href="#portfolio" class="smoothScroll" id="menu"> Help</a></li>
            <li> <a class="navbar-header"> <p class="amount" >$<%=  number_with_precision(current_user.balance, :precision => 2)%></p> <p class="balance">Balance</p>  </a></li>
            <li> <a href="/users/add_funds_form"  class="add-fund">Add Fund</a></li>
            <li class="dropdown">
                <a class="dropdown-toggle" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"><%= current_user.username %>     
                <img src="https://www.fanduel.com/images/member_defaultpic.gif" class="avatar">
                </a>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                  <li><a href="/users/<%= current_user.id %>">Profile</a></li>
                  <li><a href="/games/new">Create Game</a></li>
                  <li><a href="/users/<%=current_user.id %>/games">Your Games</a></li>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to "Log out", "/users/sign_out", :method => :delete %></li>
                </ul>
            </li>
          <% end %>
          <% if !current_user && !request.original_url.include?("sign_in")%>
            <li><a class='signup' ><%= link_to "Sign Up", "/users/sign_up" %></a></li>
            <li><a class='login' ><%= link_to "Log In", "/users/sign_in" %></a></li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>


  <%= yield %>
</body>
</html>




  

app/views/users/add_funds_form.html.erb
<div class="container">
  <div class="form-box">
    <div class="form-header">
      <h2>Add Funds</h2>
    </div>
    <div class="form-body">
      <%= form_tag "/users/add_funds", method: :post do %>
        <div class="form-group">
          <label>Amount</label>
          <div class="input-group">
            <span class="input-group-addon">$</span>
            <%= text_field_tag :balance, nil, class: "form-control", placeholder: "0.00" %>
          </div>
        </div>
        <%= submit_tag 'Add Fund', class: "btn btn-primary new_game_button" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="form-box">
    <div class="form-header">
      <h2>Edit Profile</h2>
    </div>
    <div class="form-body">
      <%= form_tag "/users/#{current_user.id}", method: :patch do %>
        <div class="form-group">
          <label>First name</label>
            <%= text_field_tag :first_name, current_user.first_name, class: "form-control", placeholder: "First name" %>
        </div>
        <div class="form-group">
          <label>Last name</label>
            <%= text_field_tag :last_name, current_user.last_name, class: "form-control", placeholder: "Last name" %>
        </div>
        <div class="form-group">
          <label>Username</label>
            <%= text_field_tag :username, current_user.username, class: "form-control", placeholder: "Username" %>
        </div>
        <%= submit_tag 'Update', class: "btn btn-primary new_game_button"  %>
        
      <% end %>
    </div>
  </div>
</div>

app/views/users/games.html.erb
<div class="container">
<div class="games-index-table">
  <div class="games-index-header">
    <h2 class="games-index"><%= @user.username %>'s games</h2>
  </div>

  <div class="games-index-body">

  <table class="table table-striped">
      <thead>
        <tr>
          <th class="row-header">ID</th>
          <th class="row-header">Games</th>
          <th class="row-header">Bet Amount</th>
          <th class="row-header">Prizes</th>
          <th class="row-header">Schedule</th>
          <th class="row-header">Banker</th>
          <th class="row-header">Scores</th>
          <th></th>
        </tr>
      </thead>
      <% @user_games.each do |game| %>
        <tbody>
          <tr class="index-row">
            <td class="game-index"><%= game.id %></td>
            <td class="game-index"><%= game.name %></td>
            <td class="game-index">$<%= number_with_precision(game.bet_amount, :precision => 2)%></td>
            <td class="game-index">$<%= number_with_precision(game.bet_amount * 90, :precision => 2) %></td>
            <td class="game-index"><%= game.start_time.strftime("%b %e, %l:%M %p") %></td>
            <td class="game-index"><%= game.banker %></td>
            <% if game.winning_score != 0 %>
              <td class="game-index"><%= game.winning_score.to_s + "-" + game.losing_score.to_s %></td>
            <%  else %>
              <td></td>
            <% end %>
            <td class="game-index"><a type="button" class="btn btn-primary btn-sm" id="join-button" href="/games/<%= game.id %>">Enter</a></td>
          </tr>
        </tbody>
      <% end %>
    </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
<div class="games-index-table">
  <div class="games-index-header">
    <h2>User Profile</h2>
  </div>
  <div class="games-index-body">
  <table class="table table-striped">
      <thead>
        <tr>
          <th class="row-header">First Name</th>
            <th class="row-header">Last Name</th>
            <th class="row-header">Username</th>
            <th class="row-header">Email</th>
            <th></th>
        </tr>
      </thead>
      <% if current_user %>
        <tbody>
          <tr class="index-row">
            <td class="game-index"><%= current_user.first_name %></td>
            <td class="game-index"><%= current_user.last_name %></td>
            <td class="game-index"><%= current_user.username %></td>
            <td class="game-index"><%= current_user.email %></td>
            <td class="game-index"><a href="/users/<%= current_user.id %>/edit">EDIT</a></td>
        </tbody>
      <% end %>
    </table>
    </div>
  </div>
</div>

      
      